version: "3.8"

services:
    laravel:
        build: .
        ports:
            - "80:80"
        environment:
            - APP_ENV=production
            - APP_KEY=base64:YOUR_APP_KEY_HERE
            - APP_DEBUG=false
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
        depends_on:
            - db

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
