version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        ports:
            - "8080:80"
        environment:
            - APP_ENV=production
            - APP_KEY=base64:+DNfMqQunx0TK0Xbv5bjMmPfvDzPOant4xiIVsVphiM=
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=railway
            - DB_USERNAME=root
            - DB_PASSWORD=luNEDoWehhDwTHweOOOIndsfwcXXPtHQ
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            - MYSQL_DATABASE=railway
            - MYSQL_ROOT_PASSWORD=luNEDoWehhDwTHweOOOIndsfwcXXPtHQ
        ports:
            - "3307:3306"
